services:
# Nome da pasta que ficara no docker(pode ser qualquer nome)
  app:
  # Local onde está o Dockerfile
    build: ..
    container_name: whatsapp_bot
    volumes:
      - ..:/app
 #    - ./src/modules/WhatsappWebBot/public:/app/src/modules/WhatsappWebBot/public
 #    - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: meubanco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

  