services:
# Nome da pasta que ficara no docker(pode ser qualquer nome)
  app:
  # Local onde está o Dockerfile
    build: ..
    container_name: whatsapp_bot
    volumes:
      - ..:/app
 #     - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: ../.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
