services:
# Nome da pasta que ficara no docker(pode ser qualquer nome)
  app:
  # Local onde está o Dockerfile
    build: ..
    container_name: whatsapp_bot
    volumes:
      - ..:/app
 #    - ./src/modules/WhatsappWebBot/public:/app/src/modules/WhatsappWebBot/public
 #    - /app/node_modules
    ports:
      - "3000:3000"
    restart: always
    command: npm run dev
    depends_on:
      - db
    environment:
      # Passe aqui as variáveis necessárias para seu app se conectar ao banco,
      # por exemplo:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      DB_DATABASE: meubanco


  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file: ../.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: meubanco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: ../.env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@exemplo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
  postgres_data: